trigger:
- none

pool:
  vmImage: 'windows-2019'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
    architecture: 'x64'

- bash: |
    pip install numpy
  displayName: Install Numpy

- powershell: |
    choco install bazel --version 3.3.1 --yes --allow-downgrade
  displayName: Install Bazel

- bash: |
    wget https://github.com/tensorflow/tensorflow/archive/v2.3.0-rc2.tar.gz
    tar -zxf v2.3.0-rc2
  displayName: unpack tensorflow source

- bash: |
    cd tensorflow-2.3.0-rc2
    export PYTHON_BIN_PATH=$(which python)
    export USE_DEFAULT_PYTHON_LIB_PATH=True
    export TF_ENABLE_XLA=False
    export TF_NEED_OPENCL_SYCL=False
    export TF_NEED_ROCM=False
    export TF_NEED_CUDA=False
    export TF_NEED_MPI=False
    export TF_DOWNLOAD_CLANG=False
    export TF_SET_ANDROID_WORKSPACE=False
    export TF_CONFIGURE_IOS=False
    export TF_OVERRIDE_EIGEN_STRONG_INLINE=True
    export TF_VC_VERSION=16.6
    export CC_OPT_FLAGS = "/arch:AVX"
    python ./configure.py
    bazel build --config=opt --verbose_failures -s //tensorflow:tensorflow_cc
  displayName: Configure and Build Tensorflow C++ API